licenses(["notice"])

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "desktop_tflite_calculators",
    deps = [
        "//mediapipe/calculators/util:simple_flow_calculator",
    ],
)
